import {
  IconAperture,
  IconCopy,
  IconLayoutDashboard,
  IconLogin,
  IconMoodHappy,
  IconTypography,
  IconUserPlus,
} from "@tabler/icons-react"
import PageviewIcon from "@mui/icons-material/Pageview"
import EditNoteIcon from "@mui/icons-material/EditNote"
import { uniqueId } from "lodash"
import SummarizeIcon from "@mui/icons-material/Summarize"
import AddHomeWorkIcon from "@mui/icons-material/AddHomeWork"
import PendingActionsIcon from "@mui/icons-material/PendingActions"
import FormatListBulletedIcon from "@mui/icons-material/FormatListBulleted"
import AssessmentIcon from "@mui/icons-material/Assessment"
import RotateLeftIcon from "@mui/icons-material/RotateLeft"
import EventNoteIcon from "@mui/icons-material/EventNote"
import CalendarMonthIcon from "@mui/icons-material/CalendarMonth"
import AccessTimeIcon from "@mui/icons-material/AccessTime"
import EventIcon from "@mui/icons-material/Event"
import StarBorderPurple500Icon from "@mui/icons-material/StarBorderPurple500"
import GroupIcon from "@mui/icons-material/Group"

const ROLES = [
  "Asst. Section Officer Admin I",
  "Asst. Section Officer Admin IV",
  "Section Officer Admin I",
  "Section Officer Admin IV",
  "Under Secretary O&M",
  "Deputy Secretary Admin",
  "Joint Secretary Admin",
  "Asst. Section Officer General II",
  "Section Officer General II",
  "Under Secretary General II",
  "Deputy Secretary General",
  "Joint Secretary General",
  "Accounts I",
  "Accounts II",
  "Accounts IV",
  "F&BO",
  "System Admin", // remove this for bill routing page
  "PAO",
  "Forwarded To Bank",
]
const Menuitems: any = {
  "Joint Secretary Admin": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "Section Officer Admin I": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    {
      id: uniqueId(),
      title: "Ex Chairman & Members",
      icon: StarBorderPurple500Icon,
      href: "/Formers",
      present: "yes",
    },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "System Admin": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    {
      id: uniqueId(),
      title: "Ex Chairman & Members",
      icon: StarBorderPurple500Icon,
      href: "/Formers",
      present: "yes",
    },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Users",
      icon: GroupIcon,
      href: "/Users",
      present: "yes",
    },
  ],
  "Asst. Section Officer Admin I": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "Asst. Section Officer Admin IV": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "Section Officer Admin IV": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "Under Secretary": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "Deputy Secretary Admin": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],

  "Asst. Section Officer General II": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "Section Officer General II": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "Under Secretary General II": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "Deputy Secretary General": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "Joint Secretary General": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "Accounts I": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "Accounts II": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "Accounts IV": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "F&BO": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  PAO: [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  "Forwarded To Bank": [
    {
      navlabel: true,
      subheader: "Home",
    },
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Bills",
      icon: EditNoteIcon,
      href: "/Bills",
      present: "yes",
    },

    {
      id: uniqueId(),
      title: "Bill Routing",
      icon: EditNoteIcon,
      href: "/BillRouting",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Ex Chairman & Members",
    //   icon: StarBorderPurple500Icon,
    //   href: "/Formers",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "System Logs",
      icon: StarBorderPurple500Icon,
      href: "/SystemLogs",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "General Report",
    //   icon: EventNoteIcon,
    //   href: "/GeneralReport",
    //   present: "yes",
    // },

    // {
    //   id: uniqueId(),
    //   title: "Pendency  Report",
    //   icon: PendingActionsIcon,
    //   href: "/PendencyReport",
    //   present: "yes",
    // },
    {
      id: uniqueId(),
      title: "List of all Bills",
      icon: FormatListBulletedIcon,
      href: "/ListOfAllBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "User Bills",
      icon: EditNoteIcon,
      href: "/UserBills",
      present: "yes",
    },
    // {
    //   id: uniqueId(),
    //   title: "Reset Bill Status",
    //   icon: RotateLeftIcon,
    //   href: "/ResetBillStatus",
    //   present: "no",
    // },
    // {
    //   id: uniqueId(),
    //   title: "Reports",
    //   icon: EditNoteIcon,
    //   href: "/Reports",
    //   present: "yes",
    // },

    {
      id: uniqueId(),
      title: "Date Wise Report",
      icon: CalendarMonthIcon,
      href: "/DateWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Monthly Report",
      icon: EventIcon,
      href: "/MonthlyWiseReport",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Yearly Report",
      icon: AccessTimeIcon,
      href: "/YearlyWiseReport",
      present: "no",
    },
    // {
    //   id: uniqueId(),
    //   title: "Users",
    //   icon: GroupIcon,
    //   href: "/Users",
    //   present: "yes",
    // },
  ],
  former: [
    {
      id: uniqueId(),
      title: "Dashboard",
      icon: IconLayoutDashboard,
      href: "/Home",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "Add Bill",
      icon: AssessmentIcon,
      href: "/Formers/AddBills",
      present: "no",
    },
    {
      id: uniqueId(),
      title: "View Bill",
      icon: EventIcon,
      href: "/Formers/ViewBill",
      present: "no",
    },
  ],
}
// ViewBill

export default Menuitems
