import { BILL_TYPE, ROLES, VALIDATION_TYPE } from "./constants"

const FIELDS_MANAGE_BILL = [
  {
    id: "diaryNumber",
    fieldName: "Diary Number",
    type: "number",
    placeholder: "Enter diary number here",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "claimReceivingDate",
    fieldName: "Claim Receiving Date (DD-MM-YYYY)",
    type: "date",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "billType",
    fieldName: "Bill Type",
    type: "select",
    placeholder: "Select a bill type",
    selectOptions: BILL_TYPE,
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "billNumber",
    fieldName: "Bill No.",
    type: "select",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "name",
    fieldName: "Name",
    type: "text",
    placeholder: "Enter name here",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "email",
    fieldName: "E-mail",
    type: "text",
    placeholder: "Enter email here",
    required: true,
    validationType: VALIDATION_TYPE.email,
  },
  {
    id: "phone",
    fieldName: "Phone",
    type: "number",
    placeholder: "Enter phone number here",
    required: true,
    validationType: VALIDATION_TYPE.mobile,
  },
  {
    id: "fileNumber",
    fieldName: "File Number",
    type: "number",
    placeholder: "Enter file number here",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "claimPeriodFrom",
    fieldName: "Claimed Period From",
    type: "date",
    required: true,
    validationType: VALIDATION_TYPE.dateRangeStart,
  },
  {
    id: "claimPeriodTo",
    fieldName: "Claimed Period To",
    type: "date",
    required: true,
    validationType: VALIDATION_TYPE.dateRangeEnd,
  },
  {
    id: "totalClaimedAmount",
    fieldName: "Total Claimed Amount",
    type: "number",
    placeholder: "Enter total claimed amount here",
    required: true,
    validationType: VALIDATION_TYPE.amount,
  },
  {
    id: "totalAdmissibleAmount",
    fieldName: "Total Amissible Amount",
    type: "number",
    placeholder: "Enter total admissible amount here",
    required: true,
    validationType: VALIDATION_TYPE.amount,
  },
  // {
  //   id: "maxAdmissibleAmount",
  //   fieldName: "Max Amissible Amount",
  //   type: "number",
  //   placeholder: "Enter max admissible amount here",
  //   required: true,
  //   validationType: VALIDATION_TYPE.amount,
  // },
  {
    id: "currentStatus",
    fieldName: "Status",
    type: "select",
    selectOptions: [
      "Open",
      "Under Processing",
      "Submitted for Approval",
      "Approved",
      "Return",
      "Not Approved",
      "Closed after Approval",
    ],
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "lastForwardedTo",
    fieldName: "Forward To",
    type: "select",
    selectOptions: ROLES,
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "currentremark",
    fieldName: "Comments",
    type: "text",
    placeholder: "Enter your remark here",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
]

const FIELDS_MANAGE_BILL_UPDATE = [
  {
    id: "sanctionedAmount",
    fieldName: "Sanctioned Amount",
    type: "number",
    placeholder: "Enter sanctioned amount here",
    required: true,
    validationType: VALIDATION_TYPE.amount,
  },

  {
    id: "PFMS",
    fieldName: "PFMS",
    type: "number",
    placeholder: "Enter pfms amount here",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "billProcessingStartDate",
    fieldName: "Bill Processing Start Date",
    type: "date",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
]

const FIELDS_MANAGE_FORMERS = [
  {
    id: "name",
    fieldName: "Name",
    type: "text",
    placeholder: "Enter name here",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "status",
    fieldName: "Status",
    type: "select",
    selectOptions: ["Present", "Ex"],
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "designation",
    fieldName: "Designation",
    type: "select",
    selectOptions: ["Chairman", "Member"],
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "phone",
    fieldName: "Phone",
    type: "number",
    placeholder: "Enter phone number here",
    required: true,
    validationType: VALIDATION_TYPE.mobile,
  },
  {
    id: "email",
    fieldName: "E-mail",
    type: "text",
    placeholder: "Enter email here",
    required: true,
    validationType: VALIDATION_TYPE.email,
  },
  {
    id: "password",
    fieldName: "Password",
    type: "password",
    placeholder: "Enter password here",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "isActive",
    fieldName: "Active",
    type: "select",
    selectOptions: ["Active", "Inactive"],
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "bankAccountNumber",
    fieldName: "Bank A/C",
    type: "number",
    placeholder: "Enter bank account number here",
    required: true,
    validationType: VALIDATION_TYPE.matchOne,
  },
  {
    id: "confirmBankAccountNumber",
    fieldName: "Confirm Bank A/C",
    type: "number",
    placeholder: "Confirm bank account number here",
    required: true,
    validationType: VALIDATION_TYPE.matchTwo,
  },
  {
    id: "ifscCode",
    fieldName: "IFSC Code",
    type: "text",
    placeholder: "Enter ifsc code here",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },

  {
    id: "bankName",
    fieldName: "Bank Name",
    type: "text",
    placeholder: "Automatically fetched with ifsc code",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },

  {
    id: "branchName",
    fieldName: "Branch Name",
    type: "text",
    placeholder: "Automatically fetched with ifsc code",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
]

const FIELDS_USERS = [
  {
    id: "role",
    fieldName: "Role",
    type: "text",
    placeholder: "User Role",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "name",
    fieldName: "User Name",
    type: "text",
    placeholder: "Enter name here",
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "email",
    fieldName: "E-Mail",
    type: "text",
    placeholder: "Enter email here",
    required: true,
    validationType: VALIDATION_TYPE.email,
  },
  {
    id: "phone",
    fieldName: "Phone",
    type: "number",
    placeholder: "Enter phone number here",
    required: true,
    validationType: VALIDATION_TYPE.mobile,
  },
]

const FIELDS_FORMERS_ADD_BILL = [
  {
    id: "billType",
    fieldName: "Bill Type",
    type: "select",
    selectOptions: BILL_TYPE,
    required: true,
    validationType: VALIDATION_TYPE.none,
  },
  {
    id: "claimedAmount",
    fieldName: "Amount",
    type: "number",
    placeholder: "Enter amount here",
    required: true,
    validationType: VALIDATION_TYPE.amount,
  },
  {
    id: "billPeriodFrom",
    fieldName: "Bill Period From",
    type: "date",
    required: true,
    validationType: VALIDATION_TYPE.dateRangeStart,
  },
  {
    id: "billPeriodTo",
    fieldName: "Bill Period To",
    type: "date",
    required: true,
    validationType: VALIDATION_TYPE.dateRangeEnd,
  },
  {
    id: "billFilePath",
    fieldName: "Upload File (Allowed: PDF, JPEG, JPG, PNG)",
    type: "file",
    required: true,
    validationType: VALIDATION_TYPE.file,
  },
]

export {
  FIELDS_MANAGE_BILL,
  FIELDS_MANAGE_BILL_UPDATE,
  FIELDS_MANAGE_FORMERS,
  FIELDS_USERS,
  FIELDS_FORMERS_ADD_BILL,
}
